#!/bin/bash

#connect mysql
echo "mysql root password:"
read rootpass
if [[ $rootpass ]]; then
mysql -uroot -p$rootpass <<EOF
-- create db
CREATE DATABASE clinic_cure;
-- create tables
use clinic_cure;


EOF
fi

