/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panels;

import controller.main.ReportController;
import view.components.main.components.table.Table;

import java.time.LocalDate;

/**
 *
 * @author Chi Cute
 */
public class DailyRecord extends javax.swing.JPanel {

    /**
     * Creates new form RecordTurnover
     */
    public DailyRecord() {
        initComponents();
        recordTable.fixTable(jScrollPane1);
    }

    public void addData(LocalDate start, LocalDate end){
        ReportController.addDataDailyReport(this.recordTable, start, end);
    }

    public void addData(){
        ReportController.addDataDailyReport(this.recordTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recordTable = new Table();

        recordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Doanh thu", "Lượt khám"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recordTable.setFocusable(false);
        recordTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(recordTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private Table recordTable;
    // End of variables declaration//GEN-END:variables


    public Table getRecordTable() {
        return recordTable;
    }

    public void setRecordTable(Table recordTable) {
        this.recordTable = recordTable;
    }
}
